### PR TITLE
programs.rofi: update to latest home-manager; add i3 swap workspaces feature

### PR DESCRIPTION
**Pull request by kalbasit**
Importing changes I did downstream to the Rofi support:
- It now supports home-manager's master branch, but broken on release 20.09).
- Added support for swapping i3 workspaces (similar to dynamic window managers).
- The list workspaces function have also been updated:
  - [rofi/i3-support: get the list of profiles and stories before sorting](https://github.com/kalbasit/soxincfg/commit/7a580d74d7b311d46ecf6be2a791b4448e655425)
  - [rofi/i3-support: include the list of all available stories from all profiles](https://github.com/kalbasit/soxincfg/commit/8a5fc98f698c70378af9a596725fd4153ea159e3)
  - [rofi/i3-support: exclude the current workspace from the printed list](https://github.com/kalbasit/soxincfg/commit/4d089a1bc6279b6f0f0eb8c58c9e2b672b187338#diff-624b4059df9856cf5204b36ffdbaa40d538514e4847768eb0e55a1de81523b8e)

NOTE: This was extracted from #29 and tested only in that branch.

### CODE REVIEW

**Comment by rissson** [comment]
Do you mind if we wait for 21.05 to merge this if it's broken on home-manager's `20.09`?

**Comment by kalbasit** [comment]
> Do you mind if we wait for 21.05 to merge this if it's broken on home-manager's `20.09`?

IMO we need to start preparing for it. What if you create a `release-20.09` branch of the existing main?

**Comment by rissson** [comment]
> What if we create a release-20.09 branch of the existing main?
Sounds good!

**Review by rissson — APPROVED** [review]

**Comment by kalbasit** [comment]
done!

**Pull request merged**
